#!/usr/bin/env python3
"""The stale `grp:win_space_toggle` clear, against real files (issue #69).

An xkb `grp:` toggle matches modifiers loosely, so an install still carrying
`hyprland.input.kbOptions = "grp:win_space_toggle"` breaks two keybinds at
once: Super+Space fires both the xkb toggle and the compositor bind, two
switches that cancel, so the OSD announces a layout change that did not
happen; Super+Alt+Space switches the layout on top of toggling window float.

The clear shipped once and fixed neither, and nothing noticed, because there
was no test. Both failure modes live in on-disk state a unit test does not
construct, which is what makes this worth a process launch:

  * the clear was guarded by a persisted marker, and a marker records that the
    check ran, not that the value was ever present. Every install whose
    config-directory migration declined burned it against the installer's
    default and then received the real config afterwards;
  * the option reaches Hyprland through the generated
    `hypr/hyprland/shellOverrides/main.lua`, not `config.json`. Nothing
    rewrites that file at startup, so clearing the config alone left the
    compositor toggling layouts indefinitely.

Needs a Wayland session and `qs` on PATH, so it skips in CI the same way the
other runtime harnesses do.
"""

import json
import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HARNESS = ROOT / "KbOptionsRuntimeTest.qml"
SHIPPED_DEFAULT = ROOT / "defaults/config.json"

STALE = "grp:win_space_toggle"
# The one non-empty value the settings control actually offers.
LEGITIMATE = "grp:alt_shift_toggle"

# As the configurator writes it. The marker comment is what lets it find the
# line again, so the fixture has to carry one.
LUA_HEADER = "-- DO NOT EDIT THIS FILE. IT IS MANAGED BY THE SHELL\n"
LUA_ROUNDING = 'hl.config({ decoration = { rounding = 22 } })\n'


# The harness prints how many checks it ran. This number is a literal rather
# than anything read back from that output: a harness whose step list shrinks
# must redden here instead of reporting `failures: 0` for a shorter run.
EXPECTED_CHECKS = 1


def _runtime_available():
    return bool(os.environ.get("WAYLAND_DISPLAY")) and shutil.which("qs") is not None


@unittest.skipUnless(_runtime_available(),
                     "needs a Wayland session and qs on PATH")
class KbOptionsMigrationRuntimeTest(unittest.TestCase):
    def setUp(self):
        self.home = Path(tempfile.mkdtemp(prefix="imi-kboptions-runtime-"))
        self.addCleanup(shutil.rmtree, self.home, ignore_errors=True)
        self.config_home = self.home / "config"
        self.shell_config = self.config_home / "immaterial-impulse"
        self.shell_config.mkdir(parents=True)
        self.overrides = self.config_home / "hypr/hyprland/shellOverrides"
        self.overrides.mkdir(parents=True)

    @property
    def config_file(self):
        return self.shell_config / "config.json"

    @property
    def lua_file(self):
        return self.overrides / "main.lua"

    def seed(self, kb_options, extra=None, lua_kb_options=None):
        config = json.loads(SHIPPED_DEFAULT.read_text())
        config["hyprland"]["input"]["kbOptions"] = kb_options
        # Nothing here should depend on the upstream-key conversion also
        # running; mark it done so the two migrations stay independent.
        config["migratedUpstreamSchema"] = True
        config.update(extra or {})
        self.config_file.write_text(json.dumps(config, indent=2))

        lua = LUA_HEADER + LUA_ROUNDING
        if lua_kb_options is not None:
            lua += f'hl.config({{ input = {{ kb_options = "{lua_kb_options}" }} }})\n'
        self.lua_file.write_text(lua)

    def launch(self, expected):
        env = dict(os.environ)
        env["XDG_CONFIG_HOME"] = str(self.config_home)
        env["XDG_STATE_HOME"] = str(self.home / "state")
        env["XDG_CACHE_HOME"] = str(self.home / "cache")
        env["XDG_DATA_HOME"] = str(self.home / "data")
        env["KBOPT_EXPECT"] = expected
        proc = subprocess.run(["qs", "-p", str(HARNESS)], cwd=str(ROOT), env=env,
                              capture_output=True, text=True, timeout=180)
        output = proc.stdout + proc.stderr
        failed = [line for line in output.splitlines() if "FAIL" in line]
        self.assertEqual(failed, [], f"harness reported failures:\n{output}")
        self.assertIn(f"[KbOptions] checks: {EXPECTED_CHECKS} failures: 0", output,
                      f"harness did not finish cleanly:\n{output}")
        return output

    def stored_kb_options(self):
        return json.loads(self.config_file.read_text())["hyprland"]["input"]["kbOptions"]

    def test_a_stale_toggle_is_cleared_from_the_config(self):
        self.seed(STALE, lua_kb_options=STALE)
        self.launch("")
        self.assertEqual(self.stored_kb_options(), "")

    def test_the_generated_lua_the_compositor_reads_is_cleared_too(self):
        """The half that made the config-only fix read as no fix at all:
        Hyprland never looks at config.json."""
        self.seed(STALE, lua_kb_options=STALE)
        self.launch("")
        lua = self.lua_file.read_text()
        self.assertNotIn("kb_options", lua,
                         "the managed kb_options line outlived the config clear")
        self.assertIn("rounding = 22", lua,
                      "clearing kb_options must not disturb other managed lines")

    def test_a_burned_marker_does_not_block_the_clear(self):
        """The exact state this shipped in: the marker recorded a check that
        ran against a config not yet carrying the value."""
        self.seed(STALE, extra={"migratedKbOptionsGrpToggle": True},
                  lua_kb_options=STALE)
        self.launch("")
        self.assertEqual(self.stored_kb_options(), "")

    def test_the_dead_marker_is_dropped_from_the_config(self):
        self.seed(STALE, extra={"migratedKbOptionsGrpToggle": True},
                  lua_kb_options=STALE)
        self.launch("")
        self.assertNotIn("migratedKbOptionsGrpToggle",
                         json.loads(self.config_file.read_text()))

    def test_a_config_already_cleared_still_gets_its_lua_purged(self):
        """Everyone who ran the config-only fix. Their config.json is clean, so
        a purge keyed on it skips them - and their compositor keeps the
        option."""
        self.seed("", lua_kb_options=STALE)
        self.launch("")
        self.assertNotIn("kb_options", self.lua_file.read_text(),
                         "the lua purge was gated on a config value that was already clean")

    def test_a_layout_toggle_the_user_chose_is_left_alone(self):
        """Unconditional applies to one value, not to the setting."""
        self.seed(LEGITIMATE, lua_kb_options=LEGITIMATE)
        self.launch(LEGITIMATE)
        self.assertEqual(self.stored_kb_options(), LEGITIMATE)
        self.assertIn(LEGITIMATE, self.lua_file.read_text())

    def test_a_config_with_nothing_to_clear_does_not_touch_the_lua(self):
        """The clear runs on every load now, so it has to be inert when there
        is nothing to do - it must not rewrite a file the user's other
        settings live in."""
        self.seed("")
        before = self.lua_file.read_bytes()
        self.launch("")
        self.assertEqual(self.lua_file.read_bytes(), before)


if __name__ == "__main__":
    unittest.main()
